<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
<body>

<script>
  // 선언
  //변수 선언 var let const 선언과 동시에 할당도 가능
  //선언만 된경우 기본값으로 undefined

  // undefined & null & NaN
  //undefined === false :  boolean 문맥에서
  //undefined === NaN : int 문맥에서 (undefined + 2 === NaN
  //null === 0 : int 문맥에서 (null+2 === 0

  //  // 호이스팅
  //  console.log(x === undefined); // not defined err - (x)
  //                                // true - (o)
  //  var x = 3;
  //
  //  var val = 'hello';
  //  // var val = 'world' - undefined
  //
  //  (function () {
  //    console.log(val); // undefined
  //    var val = 'world' // 호이스팅 대상 (호이스팅 후 undefined 값을 가지게 된다)
  //  })();

//  var a = 6;
//
//  if (a) { // '', 0, null, NaN, undefined, false 을 걸러
//    console.log(a);
//  }

  //예외 처리문
//
//  function myMonth() {
//
//  }
//
//  function logMyErrors(e) {
//    console.log(e);
//  }
//
//  function getMonthName (mo) {
//    mo = mo-1; // Adjust month number for array index (1=Jan, 12=Dec)
//    var months = ["Jan","Feb","Mar","Apr","May","Jun","Jul",
//      "Aug","Sep","Oct","Nov","Dec"];
//    if (months[mo] != null) {
//      return months[mo];
//    } else {
//      throw "InvalidMonthNo"; //throw keyword is used here
//    }
//  }
//
//  try { // statements to try
//    monthName = getMonthName(12); // function could throw exception
//    console.log(monthName);
//  }
//  catch (e) {
//    console.log(e);
//    monthName = "unknown";
////    logMyErrors(e); // pass exception object to error handler
//  }finally {
//    console.log('del');
//  }

//  function f() {
//    try {
//      console.log(0);
//      throw "bogus"; // 에러발생
//    } catch(e) {
//      console.log(e);
//      console.log(1);
//      return true; // this return statement is suspended -> finally {}
//                   // until finally block has completed
//      console.log(2); // not reachable ->
//    } finally {
//      console.log(3);
//      return false; // overwrites the previous "return"
//      console.log(4); // not reachable ->
//    }
//    // "return false" is executed now
//    console.log(5); // not reachable ->
//  }
//  f(); // alerts 0, 1, 3; returns false

//

  var arr = [1,2,3,4,5];

  for(var i =0; i < arr.length; i++){
    console.log(arr[i]);
  }

  var obj = {a:5,b:4,c:3,d:2,e:1};

  for(var key in obj){
    console.log('key', key);
    console.log('val', obj[key]);
  }


</script>
</body>
</html>